version: '2'

services:
  mica.presentation.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=data.mssql;Database=Mica;User Id=sa;Password=Test@1234
    ports:
      - "80"

  data.mssql:
    environment:
      - SA_PASSWORD=Test@1234
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"